### ISSUE TITLE
Issues with Eigen when installing

### ISSUE THREAD

**Issue by MaryAnnZ** [MIT-SPARK/TEASER-plusplus#105]
Hi, thank you for your code!

I just wanted to report that the installation of Eigen did not work for me as described in the README file.
Im on Ubuntu 16.04 and using apt get I got Eigen version 3.3 (according to apt list) and the archive doesnt seem to include older versions. During configuration I got an error message, that the eigen version is unknown. Even though after removing the version number in the main CMakeList file it was able to find the installed eigen package it ran into error later  when building the targets (links to target "Eigen3::Eigen" but the target was not found).

Fortunatley, I was able to find a solution for the problem:
Download Eigen version 3.3.9 (latest stable version currently) and install it manually (as described in the INSTALL file). Without any further configuration, cmake will find the package and it will also satisfy the version requirement, and I was able to build within seconds. I have already tested the python example and it also seems to work!

**Comment by jingnanshi** [comment]
Thanks! I will include this in the documentation.
