### ISSUE TITLE
[QUESTION]How about results on KITTI

### ISSUE THREAD

**Issue by wzey** [MIT-SPARK/TEASER-plusplus#110]
Hi, TEASER++ is a very helpful work! I learned much from your paper and code. Thank you!

I installed TEASER++ and run example well. I then applied it to a Lidar odometry algorithm. But when I run on KITTI data-set, I met some problems.

(1) From my reading, your API : **solve(src,tgt)** seems need the src point cloud size equals to the tgt point cloud size. I made two point cloud subset of the original. I found the code can only handle less than 13000 points or it print malloc error. (Maybe related to Eigen dynamic matrix)

(2) In KITTI, two Lidat scans (src and tgt) have overlapping and new region. From my understanding about your paper, new region measurements can be regarded as wrong matchings, so the code should be robust to them. But in my pratice on KITTI, sometimes its results are close to the ground truth, sometimes its results are significant wrong.  Did you test on KITTI or other Lidar odometry data-set?

**Comment by jingnanshi** [comment]
@wzey thank you for your interests!

1. You should understand `src` and `tgt` as corresponding point cloud points. In other words, with different point cloud sizes, you need to use feature matching algorithms to find top matching correspondences, and extract the points into `src` and `tgt`.
2. We didn't personally test on Lidar datasets, but I've read papers that use TEASER++ on KITTI with good performance.
