### ISSUE TITLE
[QUESTION]Correspondence-free Point Cloud Registeration

### ISSUE THREAD

**Issue by LeoDuhz** [MIT-SPARK/TEASER-plusplus#120]
Hi, I am carrying out experiments using TEASER++ on the dataset MVP(Multi-View Partial point cloud) for partial to full registeration. Since there isn't correspondence in advance, we have to generate it ourselves. In your paper, you introduce that all-to-all correspondence. So i downsample the pointcloud A to 44 and the pointcloud B to 63 to generate the 44*64 correspondence, but it takes so long and the computation load is so heavy for my 6-core 16GB machine. However, in your paper mentioned in XI.C it only takes 20s, i am wondering how you can make it and if i am doing some settings wrongly. I am following the default settings in examples/teaser_python_fpfh_icp/helpers.py.

By the way, do you have any other suggestions for this correspondence-free problem, and i also tried FPFH methods to get correspondence but the solution results aren't good.

Thanks a lot for your solutions and suggestions in advance.

**Comment by jingnanshi** [comment]
Hi @LeoDuhz , your timing observation is correct. The PC I used is 12 cores with 128 GB RAM. Also, one thing to notice is that the higher the outlier ratio, the sparser the graph will be (hence faster to generate). 

I will suggest you look into using a learning-based solution for generating pointwise features. Specifically, consider try PointNet++ or FCGF.
