### ISSUE TITLE
[QUESTION] Using teaser for finding the transformation that connects/merges two point clouds

### ISSUE THREAD

**Issue by ttsesm** [MIT-SPARK/TEASER-plusplus#123]
Hi @jingnanshi,

I've benn using teaser for aligning different point clouds with success. Following the example of using [fpfh+icp](https://github.com/MIT-SPARK/TEASER-plusplus/tree/develop/examples/teaser_python_fpfh_icp) worked quite nicely in my case. Now I wanted to ask whether it would be possible to use the teaser framework to merge two different point clouds. For example look on the two points clouds in the picture below:
![image](https://user-images.githubusercontent.com/10189018/145378745-74be2b2b-ee8e-499a-bf05-9bbd1164f909.png)
The two pcds connect at a specific part but they are two different instances of a bigger pcd. 

Now I manually applied a transformation to one of the two pieces:
![image](https://user-images.githubusercontent.com/10189018/145379253-b8611480-2bb5-4bd0-ae08-84c93dbd08f2.png)
and I would like to find the transformation that does not align but rather connects the two. Would that be possible with teaser?

I've continued on the suggested steps from the aforementioned example and I could see that the fpfh can extract meaningful correspondences:
![image](https://user-images.githubusercontent.com/10189018/145380070-d6b5343a-3a87-49a1-9590-d2706ef8af46.png)
and that teaser+icp can correctly identify the side that the two pcds have the similarities:
![image](https://user-images.githubusercontent.com/10189018/145380603-72be443a-31c2-43a5-b414-904130bc2412.png)
Though in reverse format. Thus, the extracted transformation is not correct since it tries to match similar points and not similar points in reverse. I was thinking whether I could play somehow either with some of the teaser of the fpfh parameter for adjusting the correspondence points and how these match to each other.

Thanks.

**Comment by jingnanshi** [comment]
Hi @ttsesm, thank you for your interest. The point clouds you are showing here are unfortunately very difficult to "merge" in the way you want it, as the geometry are a bit repetitive and there might exists multiple possible registration solutions. 

Do you have access to any additional information regarding the relative positions between the two point clouds?

**Comment by ttsesm** [comment]
> Hi @ttsesm, thank you for your interest. The point clouds you are showing here are unfortunately very difficult to "merge" in the way you want it, as the geometry are a bit repetitive and there might exists multiple possible registration solutions.
> 
It is true that there are multiple registration solutions, however from the example I can see that the correspondence points are kind of pointing to the correct side. Plus if I isolate the area that the two point clouds seem to merge I can see that the points and the geometry structure that they create is completing each other:
![image](https://user-images.githubusercontent.com/10189018/145612991-878be0ca-954b-4423-86f6-5b866f8d62a2.png)
Thus there should be a way to take advantage of this feature.

> Do you have access to any additional information regarding the relative positions between the two point clouds?
>
No, unfortunately the point clouds are randomly positioned in the space and then I am trying to find the best assembly solution. The only additional information that I could possibly make use is the texture which I have available.

**Comment by jingnanshi** [comment]
Very interesting. Usually in the existing works of point cloud registration, people find correspondences from the same points in two scans (i.e., there are overlapping regions in the two point clouds). However, in your case you are actually looking for correspondences that make the scans fit like a jigsaw puzzle. I am not confident that existing hand-crafted feature extractors will work well, given that they find points in the feature space by looking at similar local geometries, whereas in your case you need to find points with complementary local geometries.

If you can generate synthetic data easily, I suggest training a point cloud encoder-decoder network.
