### ISSUE TITLE
Is it possible to use an initialized rotation matrix to optimize rotation and translation?

### ISSUE THREAD

**Issue by happyfrank** [MIT-SPARK/TEASER-plusplus#124]
Thanks for your code and paper. It is very good.I have a question. 
I have initialized rotation matrix(about 1~4 degree error) and correspondences.
Is it possible to use those messages to get a more accurate rotation matrix and correct translation matrix?

**Comment by jingnanshi** [comment]
No. If you already have an initialized rotation matrix, then perhaps using an ICP-variant is better.

**Comment by happyfrank** [comment]
@jingnanshi That's allright, 非常感谢 0.0
