### ISSUE TITLE
Must I use FPFH first?

### ISSUE THREAD

**Issue by zikai1** [MIT-SPARK/TEASER-plusplus#127]
**Have you read the documentation?**

- [ *]  Yes

- [ ] No - then this issue will be closed.

Hi Jingnan,
  thanks for the excellent work. I have compiled the code and successfully run it. I find in the directory **examples**, there are three test cases. The first is based on the TLS without point features: **teaser_python_ply** and **teaser_cpp_ply**, the second is based on the FPFH feature: **teaser_python_fpfh_icp** and **teaser_cpp_fpfh**, and the last one is based on the learning feature: **teaser_python_3dsmooth**. I used two point clouds with outliers and ran **teaser_python_ply**, but the result is unsatisfactory. However, **teaser_python_fpfh_icp** can produce satisfactory results. My question is that must I use fpfh feature for all cases in advance? How **teaser_python_ply** return certifiable registration under outlier contamination? Thanks.

**Comment by jingnanshi** [comment]
No, you can use any feature detector you want. The solve() function just takes in corresponding points as two matrices. The certifier currently only have the C++ API, so you might need to use C++.

**Comment by zikai1** [comment]
Hi Jingnan,
thanks for your reply. If I directly input two point clouds without feature, also without advanced correspondence, like the simplest ICP, can I still get certible results? Thanks.

**Comment by zikai1** [comment]
Hi Jingnan,
Thanks. I know how to produce good registration results. Thank you very much.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MIT-SPARK/TEASER-plusplus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 凌晨3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MIT-SPARK/TEASER-plusplus] Must I use FPFH first? (Issue #127)





 
You need to formulate correspondences first. So if you decide to not use a feature detector, then you need to feed all the possible correspondences (N*(N-1)/2 where N is the number of points) into the solver. ICP can be replicated by creating correspondences by minimizing pairwise distances, but the solution might not be as good as that from using a feature detector first.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jingnanshi** [comment]
Thank you for your interest! Closing this issue now.
