### ISSUE TITLE
[QUESTION] test on my own datasets, registration failed

### ISSUE THREAD

**Issue by zener90818** [MIT-SPARK/TEASER-plusplus#130]
Thanks for your work. I try the code(WinTeaser version) on my own datasets which is collected from the realsense device(D415), 
the FPFH features are used in the test, here the results, registration failed,  can you tell me how to adapt the code on my own datasets, what's the main parameters which need to be adjusted for the point cloud data of different quality. thansk a lot.
<img width="711" alt="168007826-8a7cfa1c-561c-489a-92f8-ccebed88f41d" src="https://user-images.githubusercontent.com/38679014/168041882-8a0c235d-a411-4a61-a24b-a162e8eafcdc.png">
<img width="282" alt="168009259-f512c404-3ce6-4aa4-89e5-91bb21108b27" src="https://user-images.githubusercontent.com/38679014/168041891-907d52a7-07b6-47fa-b33d-be829c834148.png">
<img width="286" alt="168009268-ec2ff1e0-e1f7-4dd8-9c2e-d8092840349c" src="https://user-images.githubusercontent.com/38679014/168041904-e57ef6ed-59f7-4662-a37a-4b43865c4706.png">

**Comment by jingnanshi** [comment]
What feature extraction algorithm did you use?

**Comment by zener90818** [comment]
> 

the FPFH features are used.
![微信截图_20220514194405](https://user-images.githubusercontent.com/38679014/168424248-831547ed-6976-4a5e-b6ad-c004db58cf81.png)

**Comment by jingnanshi** [comment]
Can you try registering your source with itself using FPFH features?

**Comment by zener90818** [comment]
> Can you try registering your source with itself using FPFH features?

I have tried two different way to register. 
(1) From source to itself, registration success,
![捕获3](https://user-images.githubusercontent.com/38679014/168473163-2c019243-e549-49b4-8fad-44b62548075d.PNG)
(2) from source to itself  which is applied with a random rotation and translation matrix,  registration failed,
![捕获](https://user-images.githubusercontent.com/38679014/168473469-95fe0f8d-3da5-41bd-b001-7f1ebda0babc.PNG)
![捕获1](https://user-images.githubusercontent.com/38679014/168473473-b4ffaefc-eac5-41b6-b30b-aa1ed0eed411.PNG)

**Comment by jingnanshi** [comment]
Do you mind posting the entire code snippet you used for doing the self-registration experiment? My guess is the correspondence-matching part is causing this issue.

**Comment by LimHyungTae** [comment]
If there are no further questions, we will close the issue :) Thx
