### ISSUE TITLE
[QUESTION] Translation only alignment?

### ISSUE THREAD

**Issue by cclaan** [MIT-SPARK/TEASER-plusplus#134]
**Have you read the documentation?**

- [x] Yes
- [] No 

Hi, for the case of 3dof translation point cloud alignment, are there modifications to teaser that would improve speed / accuracy over just running the full rotation/scale/translation steps?  
Thanks

**Comment by jingnanshi** [comment]
You should be able to just run the translation estimator, although you need to take a look into the implementation as we don't have an existing API for translation only estimation.

**Comment by cclaan** [comment]
Thanks,
I did take a look at the translation estimation step, but it looked like the point clouds had already been pruned from the rotation / scale parts that use the correspondences. There was no way to pass correspondences directly to the translation step.

**Comment by cclaan** [comment]
Thanks I will dig in a bit further
