### ISSUE TITLE
CTest error

### ISSUE THREAD

**Issue by MasterLei9527** [MIT-SPARK/TEASER-plusplus#138]
When I run CTest, some errors has occurred in 18,44,46;
I use OMP_NUM_THREADS=12;
There still take error in 44,46
 96% tests passed, 2 tests failed out of 52

Total Test time (real) =  23.93 sec

The following tests FAILED:
	 44 - FPFHTest.CalculateFPFHFeaturesWithTeaserInterface (Failed)
	 46 - FPFHMatcherTest.MatchCase1 (Failed)
Errors while running CTest

How should I solve it? Thank you

**Comment by jingnanshi** [comment]
Can you try in the latest develop branch without using OMP_NUM_THREADS=12? Thanks.
