### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by manuelli** [MIT-SPARK/TEASER-plusplus#142]
**Have you read the documentation?**

- [x] Yes

Is there a way to access the `valid` field of `RegistrationResult` from python? It seems that in `python` the returned `result` doesn't have the field `valid.` Additionally is there a way to access the underlying certificate (or lack thereof) or check the max inlier clique size from python?

Thanks,

Lucas

**Comment by jingnanshi** [comment]
Hi @manuelli 
1. You are right that the field `valid` is not present in the Python binding. I can add that to the binding for you.
2. Max inlier clique size can be accessed from `getInlierMaxClique` method on the solver.
3. You need to run the certifier separately. 

Let me know if you have additional questions.
