### ISSUE TITLE
[QUESTION] How to suppress the too many DEBUG current mc logs?

### ISSUE THREAD

**Issue by hiyyg** [MIT-SPARK/TEASER-plusplus#143]
**Have you read the documentation?**

- [x] Yes
- [ ] No - then this issue will be closed.

Post your theoretical questions / usage questions here.

**Comment by SEUZTh** [comment]
I have the same problem.

**Comment by jingnanshi** [comment]
@SEUZTh @hiyyg This issue has been fixed in my fork of the PMC library. Please delete the downloaded PMC library (or removing `build` folder entirely), rerun CMake and compile again. Alternatively, if you want the messages back, pass in `-DPMC_ENABLE_DEBUG` as additional compiler flags to CMake.

**Comment by LimHyungTae** [comment]
If there are no further questions, we will close the issue. Thx!
