### ISSUE TITLE
[QUESTION] Is it possible to disable scaling and rotation estimation?

### ISSUE THREAD

**Issue by Scyten** [MIT-SPARK/TEASER-plusplus#146]
**Have you read the documentation?**

- [x] Yes
- [] No - then this issue will be closed.

I have a time critical problem and need only the translation estimation, rotation is 0 and scaling is 1.

Is there a way to disable the scaling estimation? 
The documentation and the registration.h answer `params.estimate_scaling = false`, but if i am right this variable is not checked by the `solve` method and the debug output states: 'Starting scale solver.' and 'Scale estimation complete.' Is it possible that this option does not work at all?

Is it possible to disable rotation estimation?
I have not found any solution for that.
If I use `solve.solveForTranslation(Matrix3Xd&, Matrix3Xd&)` directly, there is no filtering of correspondences, right?

**Comment by jingnanshi** [comment]
@Scyten Hi, the scale estimation option will disable the scale solver, but it will still try to filter out outliers using scale. Unfortunately we don't have a way to disable rotation. If you use the estimate translation function directly, it will still have inlier selection based on TLD cost.

**Comment by jingnanshi** [comment]
Alternatively, if all you need are translations, perhaps writing a custom solver with the max clique outlier rejection will be a better option.

**Comment by LimHyungTae** [comment]
If there are no further questions, we will close the issue. Thx!
