### ISSUE TITLE
Any attempts to compile on Windows yet?

### ISSUE THREAD

**Issue by mastrogiorgis** [MIT-SPARK/TEASER-plusplus#16]
Hello and thank you for uploading your code so we all have access to that!
It is very much appreciated.

Has anyone tried to compile the library in Win10 yet and VS2019?

Many thanks,

Giorgis

**Comment by jingnanshi** [comment]
Hi Giorigis,

Thank you for your interest. Unfortunately current I don't have any plans to support compilation on Windows. However, you can set up a Docker image to use TEASER++ on Windows.
