### ISSUE TITLE
[BUG] scale is 0.

### ISSUE THREAD

**Issue by 2848385707** [MIT-SPARK/TEASER-plusplus#163]
**Describe the bug**

**Have you run the unit tests?**

- [x] Yes
- [] No --- then this issue will be closed.

**Installed Dependencies**
Please report the versions of all dependencies you installed, as well as your OS.

**To Reproduce**
Please post the exact steps you executed to reproduce the bug.

**Additional context**
I used my own data set and used scale estimation. I entered my own feature matching pairs for teaser++, and finally the scale estimated by teaser++ was 0 and the rotation matrix was np.ones((1,1,1)). I wanted to know if the feature matching pairs I used were not correct enough. Thank you in advance.
![VOGC_5`B9}{QM( `143SE7O](https://user-images.githubusercontent.com/93814729/221787965-4b5c669b-3c47-4caa-b5c2-75d26138a414.png)

**Comment by jingnanshi** [comment]
It seems like the rotation noise bound set is infinite, which should not occur. Did you explicitly set the parameters for the solver when you use the Python API?

**Comment by LimHyungTae** [comment]
If there are no further questions, we will close the issue. Thx!
