### ISSUE TITLE
Installation fails with cmake ..

### ISSUE THREAD

**Issue by nofreewill42** [MIT-SPARK/TEASER-plusplus#164]
I try to install the repository with:

```
git clone --depth 1 https://github.com/MIT-SPARK/TEASER-plusplus.git
cd TEASER-plusplus
mkdir build; cd build
cmake ..
```

And the following is the output of cmake, what should I try to resolve?

TEASER-plusplus/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Enable printing of diagnostic messages.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/googletest-download
[ 11%] Performing download step (download, verify and extract) for 'googletest'
-- File already exists but no hash specified (use URL_HASH):
  file='/home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/googletest-download/googletest-prefix/src/release-1.8.1.zip'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/googletest-download/googletest-prefix/src/release-1.8.1.zip'
   timeout='none'
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
-- Retrying...
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
CMake Error at googletest-download/googletest-prefix/src/googletest-stamp/download-googletest.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/google/googletest/archive/release-1.8.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/googletest/archive/release-1.8.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/googletest/archive/release-1.8.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/googletest/archive/release-1.8.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/googletest/archive/release-1.8.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/googletest/archive/release-1.8.1.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    

CMakeFiles/googletest.dir/build.make:91: recipe for target 'googletest-prefix/src/googletest-stamp/googletest-download' failed
make[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/googletest.dir/all' failed
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMakeLists.txt:83 (add_subdirectory):
  The source directory

    /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/googletest-src

  does not contain a CMakeLists.txt file.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/pmc-download
Scanning dependencies of target pmc
[ 11%] Creating directories for 'pmc'
[ 22%] Performing download step (git clone) for 'pmc'
Cloning into 'pmc-src'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 33%] No patch step for 'pmc'
[ 44%] Performing update step for 'pmc'
Current branch master is up to date.
[ 55%] No configure step for 'pmc'
[ 66%] No build step for 'pmc'
[ 77%] No install step for 'pmc'
[ 88%] No test step for 'pmc'
[100%] Completed 'pmc'
[100%] Built target pmc
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/tinyply-download
Scanning dependencies of target pmc
[ 11%] Creating directories for 'pmc'
[ 22%] Performing download step (git clone) for 'pmc'
Cloning into 'tinyply-src'...
Note: switching to '0b9fff8e8bd4d37256554fe40cf76b2f3134377b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0b9fff8 silence CMP0048 warnings
[ 33%] No patch step for 'pmc'
[ 44%] Performing update step for 'pmc'
[ 55%] No configure step for 'pmc'
[ 66%] No build step for 'pmc'
[ 77%] No install step for 'pmc'
[ 88%] No test step for 'pmc'
[100%] Completed 'pmc'
[100%] Built target pmc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/spectra-download
Scanning dependencies of target spectral
[ 11%] Creating directories for 'spectral'
[ 22%] Performing download step (git clone) for 'spectral'
Cloning into 'spectra-src'...
Note: switching to '5c4fb1de050847988faaaaa50f60e7d3d5f16143'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5c4fb1d Use CMAKE_CURRENT_SOURCE/BINRARY_DIR for inclusion in other CMake projects
[ 33%] No patch step for 'spectral'
[ 44%] Performing update step for 'spectral'
[ 55%] No configure step for 'spectral'
[ 66%] No build step for 'spectral'
[ 77%] No install step for 'spectral'
[ 88%] No test step for 'spectral'
[100%] Completed 'spectral'
[100%] Built target spectral
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Found Sphinx: /home/predev/anaconda3/bin/sphinx-build  
-- Found Sphinx. Will build Sphinx HTML files.
-- Sphinx build location: /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/doc/sphinx_build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/pybind11-download
Scanning dependencies of target pmc
[ 11%] Creating directories for 'pmc'
[ 22%] Performing download step (git clone) for 'pmc'
Cloning into 'pybind11-src'...
Note: switching to 'v2.4.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 80d45248 v2.4.3 release
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
Cloning into '/home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/pybind11-src/tools/clang'...
Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
[ 33%] No patch step for 'pmc'
[ 44%] Performing update step for 'pmc'
[ 55%] No configure step for 'pmc'
[ 66%] No build step for 'pmc'
[ 77%] No install step for 'pmc'
[ 88%] No test step for 'pmc'
[100%] Completed 'pmc'
[100%] Built target pmc
-- Found PythonInterp: /home/predev/anaconda3/bin/python3.7 (found version "3.7.3") 
-- Found PythonLibs: /home/predev/anaconda3/lib/libpython3.7m.so
-- pybind11 v2.4.3
-- TEASER++ Python binding will be built.
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Python Interpreter Version: 3.7
-- Configuring incomplete, errors occurred!
See also "/home/predev/repos/jonatan/aggregate/MULLS/dependent_libraries/TEASER-plusplus/build/CMakeFiles/CMakeOutput.log".

**Comment by jingnanshi** [comment]
Can you try to see whether you can access the google test release url using your browser?

**Comment by nofreewill42** [comment]
If I paste it in the browser, or even wget downloads it without an issue.

**Comment by nofreewill42** [comment]
@jingnanshi so is it possible somehow to continue the installation process with having that file downloaded manually?

**Comment by jingnanshi** [comment]
@nofreewill42 Can you try the steps outlined in https://stackoverflow.com/questions/29816529/unsupported-protocol-while-download-tar-gz-package? In particular `sudo apt-get install openssl libssl-dev`

**Comment by nofreewill42** [comment]
It said the installed versions are already the latest for these.
But tried to install TEASER again and now it went through somehow!
Thanks @jingnanshi

**Comment by jingnanshi** [comment]
No problem @nofreewill42 ! It's possible that they have been updated automatically. Let me know if you have any more questions.

**Comment by nofreewill42** [comment]
Thank you! Have a nice weekend ! ^^'
