### ISSUE TITLE
How to operate the model to rotate only around the z-axis instead of in any direction

### ISSUE THREAD

**Issue by mcmingchang** [MIT-SPARK/TEASER-plusplus#167]
How to operate the model to rotate only around the z-axis instead of in any direction
![Uploading 微信图片_20230721110805.png…]()

**Comment by LimHyungTae** [comment]
You're png does not open, but I guess you want to estimate yaw? Then please try to use Quatro (here's an example code: https://github.com/MIT-SPARK/TEASER-plusplus/blob/master/examples/teaser_cpp_fpfh/quatro_cpp_fpfh.cc)
