### ISSUE TITLE
[BUG] the meaning of the param of the teaser solver

### ISSUE THREAD

**Issue by Rolin-zrl** [MIT-SPARK/TEASER-plusplus#171]
**Describe the bug**
Hello, would like to ask the meaning of the param of the teaser solver, how should it be adjusted to suit the new data set

 // Prepare solver parameters
                teaser::RobustRegistrationSolver::Params params;
                params.noise_bound = NOISE_BOUND;
                params.cbar2 = 1;   
                params.estimate_scaling = false;
                params.rotation_max_iterations = 100; 
                params.rotation_gnc_factor = 1.4;
                params.rotation_estimation_algorithm =
                        teaser::RobustRegistrationSolver::ROTATION_ESTIMATION_ALGORITHM::GNC_TLS;
                params.rotation_cost_threshold = 0.01;

**Comment by HikariS97** [comment]
It's hard to explain if you didn't read the paper.
