### ISSUE TITLE
[QUESTION] Set different noise bound for each measurement

### ISSUE THREAD

**Issue by HikariS97** [MIT-SPARK/TEASER-plusplus#178]
**Have you read the documentation?**

- [X] Yes
- [] No - then this issue will be closed.

In paper, it seems like we should assign \beta_i for each measurement. And in practice, e.g. for range measurement device, the farther the point, the greater the uncertainty. But in params structs, we can only set noise bound as a double data type. My ques is: can we set different noise bound for each measurement? or is any rationale behind the current implementation?

Thanks in advance.

**Comment by jingnanshi** [comment]
I think setting a different noise bound for each measurement should be doable --- you should try it out yourself by modifying the places where it's using a fixed noise bound and see the performance. I'll happy to look at PRs.
