### ISSUE TITLE
malloc(): largebin double linked list corrupted (nextsize)

### ISSUE THREAD

**Issue by chrischoy** [MIT-SPARK/TEASER-plusplus#18]
I am getting this error `malloc(): largebin double linked list corrupted (nextsize)` intermittently and can't run this for more than 5 registration pairs.

**Comment by jingnanshi** [comment]
Haven't seen this before. How large is your RAM?

**Comment by chrischoy** [comment]
It is 32G. It seems that FCGF gives too many inliers for TEASER and allocating too much memory.

**Comment by jingnanshi** [comment]
For reference: error msg is from here: https://github.com/kraj/glibc/blob/master/malloc/malloc.c#L3868

**Comment by manhvuvan281** [comment]
I tried on Intel CPU : OK,
but on AMD CPU: corrupted (malloc).
Anyone have an idea?

**Comment by manhvuvan281** [comment]
For AMD CPU users,
Code:
	import os
	os.environ["OMP_NUM_THREADS"] = "4" 
Terminal:
	export OMP_NUM_THREADS=4  #~ Max thread
	#echo $OMP_NUM_THREADS     #show 4
        python ./filename.py
