### ISSUE TITLE
[QUESTION] when  use vscode debug,I get some errors .

### ISSUE THREAD

**Issue by Runasia** [MIT-SPARK/TEASER-plusplus#186]
**Have you read the documentation?**

- [🐟] Yes，but not very careful
- [ ] No - then this issue will be closed.

Post your theoretical questions / usage questions here.

I am a beginner,, and thank you for your assistance.

I want to debug code in vscode  ,but when i click debug button 
![image](https://github.com/MIT-SPARK/TEASER-plusplus/assets/39799280/80cf9681-e2e5-4480-9c15-46ee2457bea3)

this is my cmakelist 
cmake_minimum_required(VERSION 3.10)
project(teaser_cpp_cptry)
set(CMAKE_CXX_STANDARD 14)
FIND_PACKAGE( OpenMP REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(teaserpp REQUIRED)
add_executable(teaser_cpp_cptry teaser_cpp_cptry.cc)
target_link_libraries(teaser_cpp_cptry Eigen3::Eigen teaserpp::teaser_registration teaserpp::teaser_io OpenMP::OpenMP_CXX)
file(COPY ${CMAKE_SOURCE_DIR}/../example_data/
        DESTINATION ${CMAKE_BINARY_DIR}/example_data/
        FILES_MATCHING
        PATTERN *.ply)

I can use command --cmake .. && make   ..... /teaser_cpp_cptry  can  get  teaser_cpp_cptry ,and get result just like this .

          TEASER++ Results           
Expected rotation: 
  0.996927  0.0668736 -0.0406664
 -0.066129   0.997618  0.0194009
 0.0418676 -0.0166518   0.998978
Estimated rotation: 
  0.996658  0.0729647  0.0367288
-0.0740469   0.996832  0.0290182
-0.0344951 -0.0316408   0.998904
Error (deg): 0.0783556

Expected translation: 
 -0.115577
-0.0387705
  0.114875
Estimated translation: 
 -0.116132
-0.0390858
   0.11729
Error (m): 0.00249818

Number of correspondences: 1889
Number of outliers: 1700
Time taken (s): 0.786677 
![image](https://github.com/MIT-SPARK/TEASER-plusplus/assets/39799280/e08811f3-4d17-4d42-82e8-91c6036d232b)

so i need some change or use anther ide or debug tool ?
thanks!
I will continue to search for solutions or methods to configure .

**Comment by jingnanshi** [comment]
just to clarify your CMakeList file works in terminal but not in VSCode?

**Comment by Runasia** [comment]
> just to clarify your CMakeList file works in terminal but not in VSCode?

Yes! but i'm not sure is CMakeList Mistake or something .

**Comment by Runasia** [comment]
I find  use  "-fopenmp" in task.json can solve openMP ，but  another undefined still exists.

![image](https://github.com/MIT-SPARK/TEASER-plusplus/assets/39799280/072f7ec8-fde2-4ba9-9db7-f355ebada432)

**Comment by Runasia** [comment]
It's gcc or g++ problem?..

**Comment by Runasia** [comment]
Can't do anything ,  how to  Configure debug environment in vscode ... 
![image](https://github.com/MIT-SPARK/TEASER-plusplus/assets/39799280/e21a37bf-5ec1-4b06-b37b-e822f2695f72)
due to this ..

**Comment by Runasia** [comment]
> the std::bad_alloc might be due to memory overflow. Regarding VSCode, there seems to be a linker error but unfortunately I am not familiar with VSCode configuration.

good night ! thinks for your reply , can i know how idea or something to debug code ?  I

**Comment by Runasia** [comment]
> the std::bad_alloc might be due to memory overflow. Regarding VSCode, there seems to be a linker error but unfortunately I am not familiar with VSCode configuration.

That 's maybe due to  that i run code in VMware and memory is too small...
