### ISSUE TITLE
[Has anyone ever use teaser to marge more than 2 pointcloud together?]

### ISSUE THREAD

**Issue by Monsurat-Onabajo** [MIT-SPARK/TEASER-plusplus#189]
**Have you read the documentation?**

- [x] Yes
- [] No - then this issue will be closed.

Post your theoretical questions / usage questions here.
I'm attempting to merge six point clouds using Teaser ++. Initially, I successfully stitched two of them together. My plan was to stitch pairs to create three merged point clouds, and then continue merging these results step-by-step until all were combined. Unfortunately, this method isn't producing the expected outcomes. Has anyone tried a similar approach with multiple point clouds? If so, how did it work out for you?

**Comment by LimHyungTae** [comment]
Could you provide some snapshots or something for the unexpected outcomes please?

**Comment by Monsurat-Onabajo** [comment]
Hello, I was able to get it to work finally, I used a for loop and merge two at a time

**Comment by jingnanshi** [comment]
@Monsurat-Onabajo Great to hear!
