### ISSUE TITLE
open3d fpfh 

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [MIT-SPARK/TEASER-plusplus#25]
Is it possible that we can use open3d fpfh to use solver.solve() like teaser_cpp_fpfh example?

**Comment by jingnanshi** [comment]
Yes. TEASER++ doesn't care about what features you use, as long as you have correspondences.

If you follow this tutorial: http://www.open3d.org/docs/release/tutorial/Advanced/global_registration.html, you should be almost all set. You just need to match FPFH features using your own feature matching algorithm.

**Comment by PetropoulakisPanagiotis** [comment]
Thank you for your answer. I use open3D frequently and i try to combine it with your API.  I try to import matcher in python like teaser_cpp_fpfh but an error occured(may matcher isn't available in python). Do you have any suggestion ?

**Comment by jingnanshi** [comment]
Yes I don't have the matcher binding in Python. You can use Open3D's matcher instead.
