### ISSUE TITLE
What does it mean when solution scale is -nan?

### ISSUE THREAD

**Issue by Aimi-no** [MIT-SPARK/TEASER-plusplus#27]
Hi, I'm running Teaser-plus-plus in Python and the solution I got for one of my datasets has a scale equal to -nan. What does it mean? Does it mean that the scale could not be calculated or that there's no scale needed?

Thank you.

**Comment by jingnanshi** [comment]
@Aimi-no It is usually caused by nan values somewhere in the data values (or caused by an undefined arithmetic operation somewhere in the code). If possible, you should try to isolate the problem in the dataset and see where nan is first introduced.
