### ISSUE TITLE
Feeding TEASER-plusplus correspondences

### ISSUE THREAD

**Issue by Aimi-no** [MIT-SPARK/TEASER-plusplus#31]
Hi, when I was reading your paper I found out that correspondences can be fed to TEASER. Is there a way to do it in python? I haven't found any parameters in RobustRegistrationSolver or RobustRegistrationSolver.Params that would indicate the way to do it and I haven't found it in examples.

Thank you.

**Comment by jingnanshi** [comment]
Hi,

In python, you need to provide TEASER with `src` and `dst` (two numpy matrices), and these two matrices should have rows corresponding to each other. In other words, you should view `src` and `dst` as corresponding points, not two point clouds with arbitrary arrangements of points.

**Comment by Aimi-no** [comment]
@jingnanshi 
I see. Thank you for your answer.

**Comment by jingnanshi** [comment]
Np! @Aimi-no it should actually be corresponding columns instead of rows.
