### ISSUE TITLE
Installing on mac 

### ISSUE THREAD

**Issue by negarl** [MIT-SPARK/TEASER-plusplus#33]
Can I install it on macOS High Sierra?

**Comment by jingnanshi** [comment]
@negarl I haven't tested on macOS before unfortunately. Feel free to try & post any questions here!

**Comment by negarl** [comment]
Hi again, 
I have too much trouble installing PCL on mac. I got this error, Can you help me with it? 
"clang: error: linker command failed with exit code 1 (use -v to see invocation)"
What if I install PCL with homebrew instead of the one you used ? would it be any different?

**Comment by jingnanshi** [comment]
@negarl Hi, the core TEASER++ library does not require PCL. You should try to just compile with BUILD_TEASER_FPFH=OFF

**Comment by jingnanshi** [comment]
Closing this issue for now. Feel free to reopen if you have more questions.
