### ISSUE TITLE
Ability to use custom correspondences (Eg. Point to Line, Point to Plane associations)

### ISSUE THREAD

**Issue by ameysutavani** [MIT-SPARK/TEASER-plusplus#39]
Hello,

I was wondering if it is possible to extend TEASER-plusplus to have user-defined correspondences instead of just point-to-point associations?

For instance, CERES requires the user to define a custom CostFunction class which just overloads () operator to get current residues: 
http://ceres-solver.org/nnls_modeling.html

Can TEASER++'s api be extended so that its solve() function can take direct residues and optimization parameters?

**Comment by jingnanshi** [comment]
Hi @ameysutavani, thank you for your interest and suggestion! I took a quick look, and unfortunately I think it will require more work than simply using polymorphism for the residue functions. TEASER++ is formulated for 3D point-to-point registration only, and changing it to accept other correspondences will require some substantial changes if we want to keep the same level of performance. However, if you are interested in learning more about other geometric correspondences, you may find it helpful to take a look at a new paper from our lab: https://arxiv.org/abs/2006.06769.

**Comment by ameysutavani** [comment]
Hi @jingnanshi, thanks for the quick response! Yes, I will surely take a look at the paper; thanks for sharing.
