### ISSUE TITLE
Running Teaser++ with PCL fpfh

### ISSUE THREAD

**Issue by int-smart** [MIT-SPARK/TEASER-plusplus#40]
Hi

I am trying to build Teaser++ with PCL fpfh. I am building the library using:
`cmake .. -DBUILD_TEASER_FPFH=ON && make`
I am getting the following error:
![image](https://user-images.githubusercontent.com/10044891/87846382-71a0b680-c89d-11ea-9e17-9a224e6bf940.png)

Please let me know how can this be fixed?

I am using:
Ubuntu 18.04.4 LTS
ROS Melodic

Thanks

**Comment by jingnanshi** [comment]
Hi @int-smart, what version of PCL you are using?

**Comment by int-smart** [comment]
Hi. I have PCL version 1.8.1

**Comment by int-smart** [comment]
Any updates on this issue.

**Comment by jingnanshi** [comment]
@int-smart I haven't been able to take a look, but it's on my todo list.

**Comment by Pamphlett** [comment]
@int-smart Try something like `find_package(PCL REQUIRED)` and `include_directories` in the cmakelists.

**Comment by jingnanshi** [comment]
@int-smart Hi, you need to install PCL from source. The default PCL that comes with ROS does not play nicely with my current CMake setup.

**Comment by jingnanshi** [comment]
Feel free to reopen if you have more questions.
