### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by LAICHAO2018** [MIT-SPARK/TEASER-plusplus#44]
Thank you for you wonderful work!
I ran into a problem when I ran Mini C + + example according to your steps. I hope you can answer it.

laichao@laichao-PC:~/TEASER-plusplus/examples/teaser_cpp_ply/build$ ./teaser_cpp_ply 
./teaser_cpp_ply: error while loading shared libraries: libpmc.so: cannot open shared object file: No such file or directory

I run in Ubuntu 18.04, Thank you for your response~

**Comment by LAICHAO2018** [comment]
I've tried several times and I still can't...

**Comment by pbeeson** [comment]
Just add pmc to the target_link_libraries line in the CMake file

**Comment by qiaozhijian** [comment]
> Just add pmc to the target_link_libraries line in the CMake file

what's pmc? Could you please give a link?

**Comment by jingnanshi** [comment]
@LAICHAO2018 @qiaozhijian You should be able to fix this by running `sudo ldconfig` after installing TEASER++.

**Comment by idhamari** [comment]
I had the same error and using 


               sudo ldconfig  


solved it. Probably, it should be added to the installation instruction part.

**Comment by jingnanshi** [comment]
@idhamari Thanks for reporting. Will add it to our documentation.
