### ISSUE TITLE
could TEASER++ do 2d pointcloud registration？

### ISSUE THREAD

**Issue by JasDEng** [MIT-SPARK/TEASER-plusplus#48]
Hello, I've tried examples in the TEASER++ pkg. Your work is impressive!
I am curious that if TEASER++ could be used to align 2d pointcloud.

Thank you and best wishes.

**Comment by jingnanshi** [comment]
Hi @JasDEng, right now we don't support 2D out of the box, but you can just set z to be 0 and run the solver as it is.

**Comment by JasDEng** [comment]
Thank you very much for the fast reply and help!
