### ISSUE TITLE
How to not print "Starting scale solver..."

### ISSUE THREAD

**Issue by Liuchongpei** [MIT-SPARK/TEASER-plusplus#57]
**Have you read the documentation?**

- [x] Yes
- [ ] No - then this issue will be closed.

Hello, I tried the python sample code in "Quick start". How can it not display the prompt message in the figure below? I haven't found the set parameters. Thanks in advance.

![2345截图20201002215130](https://user-images.githubusercontent.com/34116796/94931421-520f4680-04fa-11eb-85e9-b2d8cc680a74.jpg)

**Comment by jingnanshi** [comment]
You need to edit the code to remove all the printing. Alternatively, try redirect std out to null in python:
```
import os
import sys
f = open(os.devnull, 'w')
sys.stdout = f
```
