### ISSUE TITLE
attribute error RobustRegistrationSolver in windows rest of installed

### ISSUE THREAD

**Issue by parth52** [MIT-SPARK/TEASER-plusplus#84]
i have installed all things in windows python anaconda but after installed this correctly 
there is error of attribute error that teaserpp_python doesnt have RobustRegistrationSolver

thanks

**Comment by jingnanshi** [comment]
Hi @parth52 , do you mind post the exact steps you used to install on Windows? Thanks.

**Comment by jingnanshi** [comment]
Closing due to no response.
