### ISSUE TITLE
Question about the generation of "rotation_pruned_src" and "rotation_pruned_dst"

### ISSUE THREAD

**Issue by MichaelWang1028** [MIT-SPARK/TEASER-plusplus#94]
Hi,
I have a question about the generation of "rotation_pruned_src" and "rotation_pruned_dst", why are they still generated by the result of max clique algorithm "max_clique_", but not the inliers from the rotation solver "rotation_inliers_"?

Thank you in advance.

![image](https://user-images.githubusercontent.com/24295408/115812485-0be0ec80-a424-11eb-8508-c42b897022c8.png)

**Comment by jingnanshi** [comment]
Hi @MichaelWang1028 , the naming for the variables are a bit confusing, but essentially through experiments we realized that if we feed the inliers from rotation solver to the translation solver, that will actually leads to worse translation estimate than using the max clique inliers in some cases.
