### ISSUE TITLE
Ctest (Test #18) failed

### ISSUE THREAD

**Issue by kidpaul94** [MIT-SPARK/TEASER-plusplus#96]
Hi, thank you for the great work. 
I'm merely following the documentation about compilation and installation, and encountered this error:
    
    98% tests passed, 1 tests failed out of 48

    Total Test time (real) =  32.66 sec

    The following tests FAILED:
	     18 - RegistrationTest.SolveRegistrationProblemDecoupled (SEGFAULT)
    Errors while running CTest

I'm not sure where this error comes from. 

Current system version:
Ubuntu 20.04
CMake = 3.16.3
Eigen3 = 3.3.7
PCL = 1.11.1
Boost = 1.71.0

**Comment by kidpaul94** [comment]
OMP_NUM_THREADS=12 was still the only solution for this.

**Comment by jingnanshi** [comment]
@kidpaul94 thank you for reporting the issue. You are correct, unfortunately using 12 threads is still the only solution.

**Comment by SubMishMar** [comment]
Where can I set `OMP_NUM_THREADS=12`, for me 20 tests fail.
![Screenshot from 2022-03-21 21-28-16](https://user-images.githubusercontent.com/28704031/159395820-a7baa4f8-ca18-4bd9-ba4b-433d439971aa.png)
`
